version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2-buster
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      - run: 
          name: Run tests
          command: |
            . venv/bin/activate
            make test
